spring.application.name=ThuongMaiEurekaProduct
server.port=${PORT:8080}
server.address=0.0.0.0
spring.datasource.url=jdbc:postgresql://postgres.pnpvbbqfrsjjqcezwtdx:KQqlaoS2P8020Tx7@aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.pnpvbbqfrsjjqcezwtdx
spring.datasource.password=KQqlaoS2P8020Tx7
#spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5
spring.web.resources.cache.period=3600
spring.thymeleaf.cache=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB